import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillGithub } from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import screencapture from "../public/screencapture.gif";
import resume1 from "../public/resume1.png";
import resume2 from "../public/resume2.png";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Forrest Ridgeway's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-burtons'>developedbyben</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Forrest Ridgeway</h2>
            <h3 className='text-2xl py-2'>Certified FullStack Web-Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              I am an upcoming developer looking for a place to grow my knowledge and make a name for myself. I live in Harrisburg, NC. with my spouse and new addition, Elena. 
              I can't wait to get into the field and get to work. Being fresh out of the FullStack certication program, I know I have a lot to learn, and would feel more comfortable
              working closely with a mentor to guide me as a junior developer or even an intern. Click the 'Download Resume' button in the top left to see a full breakdown of my work history, or click the github icon and get to know me a little better. 
            </p>
          </div>
          <div>
            <a className='text-5xl flex justify-center py-3' href="https://github.com/cmon-theres-gotta-be-a-name-available"><AiFillGithub/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image alt='[]' src={deved} layout="fill" objectFit='cover'/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>My Strengths</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Ever since I started my coding journey, I have been interested in user engagement. I want to build websites that consumers want to interact with, whether it be through widgets, APIs, minigames etc... I want to get past the usual glance over a website that most people give, and turn that into 
              a fun, interactive, and educational experience for consumers.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
                As a fullstack developer I have a wide range of skills across multiple different platforms and languages. Check me out to see if I would make a good fit for your team!
            </p>
          </div>
          <div>
            <div className='shadow-lg p-10 rounded-xl my-10'>
              <Image alt='[]'  src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                I am leaning towards front end development, so a large part of that is knowing how to move things around on the page to make them look presentable. I am constantly looking at new CSS templates to make designing simpler.
              </p>
            </div>
          </div>
          <div>
            <div className='shadow-lg p-10 rounded-xl my-10'>
              <Image alt='[]'  src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Elegant Coding</h3>
              <p className='py-2'>
                I like to keep my code clean with extensions like "Prettier" to make it as readable as possible for others collaborate.
              </p>
            </div>
          </div>
          <div>
            <div>
              <h3 className='text-3xl py-1 mb-20'>This is my Resume so that you wont have to risk anything with a unsecure download</h3>
            </div>
            <Image alt='[]'  src={resume1}/>
            <Image alt='[]'  src={resume2}/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='py-2'>
              This will begin my list of projects that I have worked on so far with more to come. I will be updating regularly.
            </p>
          </div>
          <div>
            <div className='shadow-lg p-10 rounded-xl my-10'>
              <Image alt='[]'  src={screencapture} width={600} height={600} />
              <a className='text-lg font-medium pt-8 pb-2' href="https://nrenner0211.github.io/dad_app/">Dad App</a>
              <p className='py-2'>
                In this project my team and I used to HTML, CSS, and Javascript to make an app. We used multiple APIs to create a multitool of a website for the stereotypical suburban father.
              </p>
            </div>
          </div>
        </section>
      </main>

    </div>
  );
}
